apiVersion: v1
kind: Template
metadata:
  name: docugate-dc-templates
labels:
  app: docugate
  template: docugate
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}${SUFFIX}
    labels:
      app: docugate
  spec:
    minReadySeconds: 20 # should be ready for atleast 20 seconds before the container is considered available. This will allow us
    # to catch any errors on deploy before they are available to the web
    replicas: 3
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
          memory: '128Mi'
        limits:
          cpu: '200m'
          memory: '256Mi'
    template:
      metadata:
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        volumes:
        - name: ${NAME}-search-config-volume
          configMap:
            name: ${NAME}-search-config
        containers:
        - image: ${NAME}:${VERSION}
          name: docugate
          ports:
          - containerPort: 4000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '200m'
              memory: '256Mi'
          volumeMounts:
          - name: ${NAME}-search-config-volume
            mountPath: /opt/app-root/src/config
            readOnly: true
          env:
          - name: DOCUMIZE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: docugate-config
                key: documizeBaseUrl
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - docugate
        from:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}${SUFFIX}
    labels:
      app: docugate
  spec:
    ports:
    - name: web
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: docugate
    annotations:
      haproxy.router.openshift.io/disable_cookies: 'true'
    name: ${NAME}${SUFFIX}
  spec:
    host:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: docugate
    name: ${NAME}-config
  data:
    documizeBaseUrl: ${DOCUMIZE_BASE_URL}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: docugate
    name: ${NAME}-search-config
  data:
    # this is the additional arguments that are passed to the documizer /api/search request body
    # in curl it would look like. 
    # curl https://docs.pathfinder.gov.bc.ca/api/search -X POST -d '{"keywords": "develop", "doc": true, "tag": true, "content": true}'
    # defaultResultLimit is not passed onto documize api, this is internally consumed
    # defaultSearchOptions are additional options that are passed to the documize /api/search POST request body
    #   doc: {Boolean} # search against document titles
    #   tag: {Boolean} # search against document tags
    #   content: {Boolean} # search against document content
    #   attachments: {Boolean} # search against document attachment titles
    index.json: |-
      {
        "defaultResultLimit": 25, 
        "defaultSearchOptions": {
          "doc": true, 
          "tag": true, 
          "content": true,
          "attachments": false 
        }
      }
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: docugate
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: A name used for routes/services and deployment configs
  displayName: Host
  name: HOST
  required: false
  value: ''
- description: Base URL of the Documize instance to be searched
  displayName: Rocket.Chat Base URL
  name: DOCUMIZE_BASE_URL
  required: true
  value: "https://docs.pathfinder.gov.bc.ca/"
